### ISSUE TITLE
Can't access fanbox.cc when pixiv-toolkit was enabled

### ISSUE THREAD

**Issue by andyboji** [leoding86/webextension-pixiv-toolkit#186] opened 2022-03-03 14:19 UTC
After update to v5.5.1
when I access to fanbox.cc, it's always show エラーが発生しました
and the page was blank
disable toolkit can resolve this
Firefox version: 97.0.1(64bit)

**Comment by leoding86** [comment] 2022-03-04 06:33
Duplicate of #183

**Closed by leoding86** 2022-03-04 06:33 UTC
