### ISSUE TITLE
WEBM generation doesn't work

### ISSUE THREAD

**Issue by turbodude** [leoding86/webextension-pixiv-toolkit#65] opened 2020-07-01 16:51 UTC
**Describe the bug**
When I click on "generate WEBM" the percentage counter starts counting up and then stucks at "Generating 100%" and nothing happens. GIFs are being generated as expected, zip archives too.

**Example work from Pixiv**
https://www.pixiv.net/en/artworks/82673860
Not just this image, any animation basically

**Browser and Version (please complete the following information):**
Firefox 77.0.1 64 bit

**Settings of extension**
https://pastebin.com/W2tzYF59

PS:
This seems to be something browser-specific, I does work for me in Chrome. In Firefox I might have turned off something in the advanced settings 🤔

**Comment by leoding86** [comment] 2020-07-02 00:55
Duplicate of #4

**Closed by leoding86** 2020-07-02 00:55 UTC
Labels: bug
