### ISSUE TITLE
option tab broken in firefox 71

### ISSUE THREAD

**Issue by yarrmateys** [leoding86/webextension-pixiv-toolkit#21] opened 2020-01-01 16:28 UTC
unsure if it's just because of a new firefox, but going to the plugin's options enters an infinite load of the page, the browser immediately eats all available ram and starts filling the pagefile up until it crashes the pc unless firefox is manually terminated from the task manager.

**Comment by leoding86** [comment] 2020-01-02 01:09
I can't reproduce the issue in Firefox 71.0 or Firefox 72.0b11. Could you disable other addons and reproduce the issue?

**Comment by yarrmateys** [comment] 2020-01-02 06:39
my bad, i forgot to mention that it's only happening through tools>add-ons>pixiv toolkit>options. the version on the icon in the toolbar works fine.

**Comment by leoding86** [comment] 2020-01-06 01:46
Fixed by disabling open options in Firefox addon page.

**Closed by leoding86** 2020-01-06 01:46 UTC
