### ISSUE TITLE
Chrome Plug-in Freezing Pixiv Tabs and Download History not registered(?)

### ISSUE THREAD

**Issue by animan095** [leoding86/webextension-pixiv-toolkit#55] opened 2020-06-11 22:20 UTC
A: Chrome is finding that Pixiv tabs are becoming unresponsive and prompts to close them
B: As of today the Download button doesn't show the checkmark for "already downloaded" works in some tabs. Even after repeated downloads

A: As of very recently the performance of Chrome has dwindled in Pixiv pages. I check for other roundabout ways to solve the problem using some functions of chrome:flags, and also disabled most of my plugins. I lastly disabled Pixiv Toolkit and the performance returned.
More thn three "right click-> open in newtab" actions would cause Pixiv to freeze.

B: Download button functions properly, but after the download, the  checkmark that usually appears at the right part does not appear. Some tabs register the "event' properly after a re-download of the work (the tab doesn't prompt the window that warns a repeated work download too)
The link of one of the works in which this happened is this one: https://www.pixiv.net/en/artworks/82193965

Chrome Ver 83.0.4103.97 (Official Build) (64-bit)

[pixiv_toolkit_settings-1591913787447.txt](https://github.com/leoding86/webextension-pixiv-toolkit/files/4767626/pixiv_toolkit_settings-1591913787447.txt)

For the sake of reference, I have very recently exported my Pixiv Toolkit history and imported in to a different user in chrome. I don't know if this could have cause the problem B

**Comment by animan095** [comment] 2020-06-15 04:49
Update
The behavior stated in this thread is only present in one of my browser users of Chrome.
The first one that I use seldom has no issues whatsoever.

**Comment by leoding86** [comment] 2020-06-21 06:21
I can reproduce issue B after import you settings, but I don't import any history. I'll fix it after I find the reason. I can't reproduce issue A.

**Comment by animan095** [comment] 2020-06-21 22:57
Thanks for the response, issue A might have been caused by the recent windows May 2020 update from what as I have read in some articles on the internet. I will hope that a patch and the rumored enhancement in the future will help.

**Comment by animan095** [comment] 2020-06-29 01:43
> I can reproduce issue B after import you settings, but I don't import any history. I'll fix it after I find the reason. I can't reproduce issue A.

I figured out what might be happening. 
The problem started when I activated the History setting.
My guess is that because I like to open many Pixiv tabs, the process of recording each history might have "confused" the program.
Nevertheless, I can say that by deactivating the History setting and restarting the browser I got my percieved performance back.

**Comment by leoding86** [comment] 2020-06-29 02:55
Thanks for the further information. I'll try reproduce it later.

**Comment by leoding86** [comment] 2020-06-29 03:47
@animan095 I opened 40+ tabs that all are animation work but didn't experience any freezing issue you mentioned. My PC has 16GB rom and the CPU is i7 6700, on ssd installed.

I think this issue might be hardware related, but I'll leave this issue open and keep the issue in eyes.

**Comment by animan095** [comment] 2020-06-29 05:23
Thank you for the quick response.
I am estranged to say that the amount of open tabs might not be the issue. 

In one of my chrome user, where the History setting is active, I opened barely 40+ pixiv tabs (alongside 20+ other website tabs). Including artworks, users, and tags tabs, and after a few cycles of "right click + open in new window" the lag became apparent. I.e. Have to wait 5+ sec to be able to interact with the page, and/or being forced to restart chrome to continue browsing, chrome prompting to kill unresponsive pages, and chrome crashing under the load after a large amount of time

On another chrome user, without the History setting active, I have over 999+ open pixiv tabs. And the lag in my  "right click + open in new window" is minimal. I.e. No waiting, no prompts. Less crashes.

Might be Hardware Related indeed, but my hardware specs do not seem that inferior processing wise. A possible reason could be that my computer is a ASUS FX504 laptop, or that I have Bitdefender antivirus installed

Proccesor: Intel Core i7 8750H, 6 Cores 12 Threads
OS: Windows 10 64 bit ver 1909 OS Build 18363.900
RAM: 24GB (8GB + 16GB)
GPU: Nvidia GTX 1050Ti 6GB
Anti-Virus: Bitdefender Total Security
Boot Drive: Intel 660p 2TB SSD partitioned into C:\ 250GB and E:\ 1.62TB
Storage Drive: D:\ Western Digital WD20SPSZX-00CRAT0 2TB

[My PC Hardware.txt](https://github.com/leoding86/webextension-pixiv-toolkit/files/4843843/My.PC.Hardware.txt)

For now my experience with your useful plugin is great. So I believe this issue is not that important for now.
If you feel like I could provide anything to help you I'll be more than glad to do so. 

As always, thank you for your hard work!

**Comment by leoding86** [comment] 2020-07-03 12:25
Close it for now. Feel free to reopen it if necessary.

**Closed by leoding86** 2020-07-03 12:25 UTC
Labels: bug
