### ISSUE TITLE
Allow extension takes over downloads no longer working since recent update

### ISSUE THREAD

**Issue by vermeeren** [leoding86/webextension-pixiv-toolkit#188] opened 2022-03-05 03:35 UTC
**Describe the bug**

Since recent update I noticed downloads were no longer worked at all. Plugin would say as if it was downloaded, but nothing showed up in downloads folder. I gave it the new permissions.

Trying to enable `Allow extension takes over downloads` does not work. After F5 the setting is disabled again, it is impossible to get it to be enabled.

**Expected behavior**

Plugin automatically save image to specified subdirectory `pixiv/` like before update.

**Example work from Pixiv**

Any work.

**Screenshots**

![Screenshot_20220305_043056](https://user-images.githubusercontent.com/5957454/156866076-7d5defb9-da64-4a58-9c85-e21ef933e52f.png)

**Browser and Version (please complete the following information):**

Firefox 91.6.0 ESR, Linux.

**Settings of extension**

<details>

```json
{
  "MangaPageNumberStartWithOne": false,
  "alwaysPack": false,
  "animationJsonFormat": 2,
  "askDownloadSavedWork": true,
  "autoActivateDownloadPanel": true,
  "disableDownloadsShelf": false,
  "displayWorkTypeLabel": true,
  "downloadPackFiles": true,
  "downloadPanelPosition": "center",
  "downloadPanelStyle": 1,
  "downloadRelativeLocation": "pixiv/",
  "downloadSaveAs": false,
  "downloadTasksWhenDownloadingImages": 5,
  "enableExtTakeOverDownloads": false,
  "enableExtend": false,
  "enableExtension": true,
  "enablePackUgoiraFramesInfo": true,
  "enablePtkSearch": true,
  "enableSaveDownloadHistory": 1,
  "enableSaveVisitHistory": true,
  "enableWhenUnderSeconds": 1,
  "extendDuration": 3,
  "featureKnown": false,
  "guideShowed": true,
  "illustrationCreateSubdirectory": 0,
  "illustrationImageRenameFormat": "u{authorId}_{id}_p{pageNum}_{title}",
  "illustrationKeepPageNumber": true,
  "illustrationPageNumberLength": -1,
  "illustrationPageNumberStartWithOne": false,
  "illustrationRelativeLocation": "",
  "illustrationRenameFormat": "u{authorId}_{id}_{title}",
  "importantNoticeDisplayed": true,
  "language": "default",
  "mangaImageRenameFormat": "u{authorId}_{id}_p{pageNum}_{title}",
  "mangaPageNumberLength": -1,
  "mangaPagesInChunk": 99,
  "mangaRelativeLocation": "",
  "mangaRenameFormat": "u{authorId}_{id}_{title}",
  "maxDownloadRecords": 10000,
  "maxHistoryItems": 10000,
  "multipleDownloadsGapTime": 150,
  "notSaveNSFWWorkInHistory": false,
  "novelIncludeDescription": false,
  "novelRelativeLocation": "",
  "novelRenameFormat": "",
  "pixivComicImageRenameFormat": "{episodeId}_{episodeTitle}_p{pageNum}",
  "pixivComicPageNumberLength": 0,
  "pixivComicPageNumberStartWithOne": false,
  "pixivComicRelativeLocation": "",
  "pixivComicRenameFormat": "{episodeId}_{episodeTitle}",
  "showPixivOmina": true,
  "showReloadInPopup": false,
  "showUpdateChangeLog": true,
  "statIllustDownloaded": 4025,
  "statMangaDownloaded": 45,
  "statNovelDownloaded": 0,
  "statUgoiraDownloaded": 29,
  "ugoiraConvertTool": "default",
  "ugoiraCustomFFmpegCommand": "",
  "ugoiraQuanlity": 1,
  "ugoiraRelativeLocation": "",
  "ugoiraRenameFormat": "u{authorId}_{id}_{title}",
  "version": "5.5.1",
  "visitHistoryType": "list",
  "workCoverSize": 1
}
```

</details>

**Additional context**

Stopped working after recent update that asked for more permissions (which I did give).

**Comment by leoding86** [comment] 2022-03-05 03:57
Duplicate of #185

**Closed by leoding86** 2022-03-05 03:57 UTC
Labels: bug

**Comment by vermeeren** [comment] 2022-03-05 15:34
@leoding86 Thank you for quick update!
