### ISSUE TITLE
Image files being downloaded as HTML

### ISSUE THREAD

**Issue by 501stRookie** [leoding86/webextension-pixiv-toolkit#176] opened 2022-02-26 19:12 UTC
**Describe the bug**
After the newest update, the files being downloaded are HTML, not the image files. It seems to affect paid posts

**Expected behavior**
I expected it to download the actual image files.

**Screenshots**
![image](https://user-images.githubusercontent.com/38931139/155856130-6501f9f4-5f5b-4bcb-98cb-d553d81c46fe.png)

**Browser and Version (please complete the following information):**
Google Chrome Version 98.0.4758.102

**Settings of extension**
You can export the settings of extension in setting page.
[pixiv_toolkit_settings-1645902629625.zip](https://github.com/leoding86/webextension-pixiv-toolkit/files/8147335/pixiv_toolkit_settings-1645902629625.zip)

**Comment by leoding86** [comment] 2022-02-27 03:25
Please provide the issue link. And the extension can't download non-free post if you haven't paid.

**Comment by 501stRookie** [comment] 2022-02-27 18:33
NSFW
I tried it on these links
https://www.fanbox.cc/@kunka/posts/3468743
https://nakai-zard.fanbox.cc/posts/3446643

And I have paid. I am trying to download the posts that I have paid for, but it downloads them as HTML.

**Comment by leoding86** [comment] 2022-02-28 05:55
Did previous version worked? I can't reproduce the issue on free works. I recommand you to re-login Fanbox and try again. And if you can, try to find a normal work and check if the extension works. For example, this one https://randowis.fanbox.cc/posts/3454704

Duplicate of #175

**Comment by CobraARX7** [comment] 2022-02-28 16:50
I'm seeing the same problem, previous version worked correctly 
it works on free posts like this one https://www.fanbox.cc/@bigshine000/posts/3464298
on the paid version it get html files https://www.fanbox.cc/@bigshine000/posts/3464248

**Comment by Pang-ops** [comment] 2022-02-28 16:52
Same issue. Works fine on free posts, downloads paid posts as .html
re-login to Fanbox doesn't fix it.

**Comment by leoding86** [comment] 2022-03-01 06:13
Alright. I just subscribed a user and started working on the issue. It shoudn't take much time to fix it.

**Closed** 2022-03-01 10:38 UTC
Labels: bug
